# Generated by Django 4.0 on 2022-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'note_table',
            },
        ),
    ]
