# Generated by Django 4.0 on 2022-03-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteNamesTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.notetable')),
            ],
            options={
                'db_table': 'note_names_table',
            },
        ),
    ]
