# Generated by Django 4.0 on 2022-03-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_notenamestable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notenamestable',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
