# Generated by Django 4.0 on 2022-04-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_notenamestable_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteNamesTable',
        ),
    ]
